music/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 11/22/16 2:58 PM
# @Author  : YangGao
# @File    : urls.py
from django.conf.urls import url
from . import views

'''namespace'''
app_name = 'music'

urlpatterns = [

    url(r'^play_song/$', views.play_song, name='play'),

    url(r'^(?P<album_id>[0-9]+)/cancel_favorite/(?P<song_id>[0-9]+)/$', views.cancel_favorite,
        name='cancel_favorite_song'),

    url(r'^(?P<album_id>[0-9]+)/favorite_song/(?P<song_id>[0-9]+)/$', views.favorite_direct, name='favorite_song'),

    url(r'^search/$', views.display_search_results, name='search'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    # url(r'album/add/$', views.AlbumCreate.as_view(), name='album_add'),
    # url(r'^[i]$', views.IndexView.as_view(), name='index'),
    url(r'^[i]$', views.index_global, name='index'),
    url(r'^(?P<pk>[0-9]+)/display/$', views.DetailView.as_view(), name='all_songs'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^$', views.index, name='index'),
    url(r'^[t]$', views.index_template, name='temp'),
    url(r'^[r]$', views.index_render, name='render'),
    url(r'^(?P<album_id>[0-9]+)/favorite/display/$', views.favorite_display, name='display_favorite'),
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/display/allById/$', views.all_songs_display_by_album_id, name='display_all_in_album'),
]

python_web_with_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
'''passport
name:admin
password:(****) login when start boot on mac screen
'''
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 11/22/16 2:40 PM
# @Author  : YangGao
# @File    : models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse

'''

(py_ve) johnsdeMacBook-Pro:python_web_with_django johnsmac$ python manage.py makemigrations music
Migrations for 'music':
  music/migrations/0001_initial.py:
    - Create model Album
    - Create model Son
(py_ve) johnsdeMacBook-Pro:python_web_with_django johnsmac$ python manage.py sqlmigrate music 0001
BEGIN;
--
-- Create model Album
--
CREATE TABLE "music_album" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
"artist" varchar(250) NOT NULL, "album_title" varchar(500) NOT NULL,
"genre" varchar(100) NOT NULL, "album_logo" varchar(1000) NOT NULL);
--
-- Create model Son
--
CREATE TABLE "music_son" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
"file_type" varchar(10) NOT NULL, "song_title" varchar(250) NOT NULL,
 "album_id" integer NOT NULL REFERENCES "music_album" ("id"));

CREATE INDEX "music_son_95c3b9df" ON "music_son" ("album_id");

COMMIT;

(py_ve) johnsdeMacBook-Pro:python_web_with_django johnsmac$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, music, sessions
Running migrations:
  Applying music.0001_initial... OK
(py_ve) johnsdeMacBook-Pro:python_web_with_django johnsmac$


'''


class Album(models.Model):

    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)
    is_local_file = models.BooleanField(default=False)
    # '''当点击添加 新专辑 按钮时 会走这方法,暂时 有URL错误 '''
    #
    # def get_absolute_url(self):
    #     reverse('music:all_songs', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + '_' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    audio_file = models.FileField(default='')

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo', 'is_local_file']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 11/22/16 2:40 PM
# @Author  : YangGao
# @File    : views.py
# from django.http import Http404
from django.http import HttpResponse
from .models import Album, Song
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from .forms import AlbumForm, UserForm, SongForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def index_render(request):
    all_albums = Album.objects.all()
    context = {
        'all_albums': all_albums
    }

    return render(request, 'music/index.html', context)


def index_template(request):
    all_albums = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = {
        'all_albums': all_albums,
    }
    return HttpResponse(template.render(context, request))


# def index(request):
#     all_albums = Album.objects.all()
#     html = ''
#
#     for album in all_albums:
#         url = '/music/' + str(album.id) + '/'
#         html += '<a href="' + url + '">' + album.album_title + '</a><span>' + \
#                 '<a href="' + album.album_logo + '"> 专辑logo</a></span><br>'
#
#     return HttpResponse(html)


def detail(request, album_id):
    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise Http404('Album does not exist')
    # '''No Album matches the given query.'''
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/detail.html', {
        'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/a.html', {
            'album': album, 'error_message': 'no song be selected '})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/b.html', {'album': album})


def favorite_direct(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    selected_song = Song.objects.get(pk=song_id)
    selected_song.is_favorite = True
    selected_song.save()
    return render(request, 'music/all_songs_by_albumID.html', {'album': album})


def cancel_favorite(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    selected_song = Song.objects.get(pk=song_id)
    selected_song.is_favorite = False
    selected_song.save()
    return render(request, 'music/all_songs_by_albumID.html', {'album': album})


''' check all of favorite songs alone  by album_id in browser'''


def favorite_display(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/b.html', {'album': album})


def all_songs_display_by_album_id(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/all_songs_by_albumID.html', {'album': album})


# class IndexView(generic.ListView):
#     template_name = 'music/index.html'
#     context_object_name = 'object_list'
#
#     def get_queryset(self):
#         return Album.objects.all()


def index_global(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        albums = Album.objects.filter(user=request.user)
        return render(request, 'music/index.html', {'object_list': albums})


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/all_songs_by_albumID.html'


# class AlbumCreate(CreateView):
#     # the name of html file must be album_form , then does work
#     model = Album
#     fields = ['artist', 'album_title', 'genre', 'album_logo']


def create_album(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        '''TODO how to hide the attr like is_local_file in form'''
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.is_local_file = True
            album.album_logo = request.FILES['album_logo']
            logo_type = album.album_logo.url.split('.')[-1]
            logo_type = logo_type.lower()
            if logo_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/album_form.html', context)
            album.save()
            return render(request, 'music/all_songs_by_albumID.html', {'album': album})

        context = {
            "form": form,
        }
        return render(request, 'music/album_form.html', context)


def delete_album(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        album = Album.objects.get(pk=album_id)
        album.delete()
        albums = Album.objects.filter(user=request.user)
        return render(request, 'music/index.html', {'object_list': albums})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'object_list': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            print('user is active', user.is_active)
            if user.is_active:
                login(request, user)
                print('user name is ', user.username)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'object_list': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def display_search_results(request):
    song_results = Song.objects.all()
    query = request.GET.get("search")
    if query:
        song_results = song_results.filter(
            Q(song_title__icontains=query)
        ).distinct()
        if song_results:
            return render(request, 'music/search_results.html', {
                'songs': song_results,
            })
        else:
            return render(request, 'music/no_answer_page.html')


def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/add_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'music/add_song.html', context)
        song.file_type = file_type
        song.save()
        return render(request, 'music/all_songs_by_albumID.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/add_song.html', context)


def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/all_songs_by_albumID.html', {'album': album})


def play_song(request):
    return render(request, 'music/player.html')

templates/music/all_songs_by_albumID.html
{% extends 'music/base.html' %}

{% block title %}{{ album.album_title }}{% endblock %}

{% block body %}

    <div class="container-fluid" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <!-- Left Album Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if album.album_logo %}
                            {% if album.is_local_file %}
                                <img src="{{ album.album_logo.url }}"
                                     width="300" height="300" class="img-responsive">
                            {% else %}
                                <img src="{{ album.album_logo }}"
                                     width="300" height="300" class="img-responsive">
                            {% endif %}
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}

                        <span class="text-muted"><h3>{{ album.artist }}</h3></span>

                        <h2 class="text-muted">{{ album.album_title }}</h2>

                        <div id="player" style="display: none">
                            <div>
                                <label id="player_son_label"></label>
                            </div>

                            <audio id="audio_controller" controls="controls">
                                <source src="">
                                Your browser does not support the audio element.
                            </audio>
                        </div>
                    </div>

                </div>
            </div>
            <!-- Right Songs Info -->
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="#">View All</a></li>
                    <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2 class="sub-header"> all Songs in {{ album.album_title }}</h2>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>name</th>
                                    <th>type</th>
                                    <th>favorite</th>
                                    <th>play/download</th>
                                    <th>delete</th>
                                </tr>
                                </thead>
                                <tbody id="play_list">
                                {% for song in album.song_set.all %}
                                    <tr>
                                        <td> {{ song.song_title }}</td>
                                        <td>{{ song.file_type }}</td>
                                        <td>
                                            {% if not song.is_favorite %}
                                                <a href="{% url 'music:favorite_song' album.id  song.id %}"
                                                   class="btn-favorite"><span
                                                        class="glyphicon glyphicon-star "></span></a>
                                            {% else %}
                                                <a href="{% url 'music:cancel_favorite_song' album.id  song.id %}"
                                                   class="btn-favorite"><span
                                                        class="glyphicon glyphicon-star active"></span></a>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <div id="play_song_button_a">
                                                <button id="play_song_button" type="button"
                                                        class="btn btn-success btn-xs"
                                                        onclick="play_my_music('{{ song.audio_file.url }}','{{ song.song_title }}')">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </div>
                                        </td>
                                        <td>
                                            <form action="{% url 'music:delete_song' album.id song.id %}" method="post"
                                                  style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                                <button type="submit" class="btn btn-danger btn-xs">
                                                    <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>

        function play_my_music(url, name) {

            var supportsAudio = !!document.createElement('audio').canPlayType;

            if (supportsAudio) {

                var player = $('#audio_controller')[0];
                var area = $('#player')[0];
                var label = $('#player_son_label')[0];
                player.src = url;
                player.play();
                area.style.display = 'block';
                label.innerText = name;
                player.addEventListener('ended', function () {

                    area.style.display = 'none';
                    if (player.playing) {
                        player.stop()
                    }
                });

            }
        }

    </script>

{% endblock %}

templates/music/b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>favorite song in {{ album.album_title }}</title>
</head>
<body>
<h2>{{ album.artist }}</h2>

{% for song in album.song_set.all %}
    <label>
        {% if song.is_favorite %}
            {{ song.song_title }}
            <img src="http://i.imgur.com/b9b13Rd.png">
        {% endif %}
    </label><br>
{% endfor %}
</body>
</html>

templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/bootstrap_base_style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <title>{% block title %}YongGao's python website{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">YongGao's python website</a>
        </div>

        <!-- items -->
        <div id="topNavBar" class="collapse  navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Profile</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'music:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    Logout</a></li>
            </ul>

            <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'music:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="song's name..."
                           value="{{ request.GET.search }}">
                </div>
                <button type="submit" class="btn btn-primary">search</button>
            </form>

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/bootstrap_base_style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body style="background:transparent url({% static 'music/background.jpg' %}) no-repeat scroll center top;">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Welcome</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a>
                </li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login' %}">Log In</a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/music/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.0/build/pure-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.0/build/grids-responsive-min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'music/base_style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <title>YongGao's python website</title>
</head>

<body>

<div class="sidebar pure-u-1 pure-u-md-1-4">
    <div class="header">
        <h2 class="brand-title">welcome my world</h2>
        <h3 class="brand-tagline">Creating a music garden using Pure</h3>

        <nav class="nav">
            <ul class="nav-list">
                <li class="nav-item">
                    <a class="pure-button" href="{% url 'music:play' %}">Test Player</a>
                </li>
                <li class="nav-item">
                    <a class="pure-button" href=" {% url 'music:create_album' %}">add album</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

<div class="content pure-u-1 pure-u-md-3-4">
    <div>
        <!-- A wrapper for all the blog posts -->
        <div class="posts">
            <h1 class="content-subhead">keep moving enjoying our life</h1>

            <!-- A single  post -->
            <section class="post">
                <header class="post-header">
                    <img width="78" height="78" alt="Tilo Mitra&#x27;s avatar" class="post-avatar"
                         src="{% static 'music/images/avatar.jpg' %}">

                    <h2 class="post-title">Showing Albums</h2>

                    <p class="post-meta">
                        By <a href="#" class="post-author">YangGao</a> under <a
                            class="post-category post-category-design" href="#">CSS</a> <a
                            class="post-category post-category-pure" href="#">Pure</a>
                    </p>
                </header>

                <div class="post-description">
                    <div class="col-sm-12">
                        <h3>{{ user.username }}'s Albums</h3>
                    </div>
                    {#  <!-- {% if all_albums %}  for def view's parameter-->#}
                    {% if object_list %}

                        {# <!--{% for album in all_albums %} for normal def url view-->#}
                        {% for album in object_list %}
                            <div class="col-sm-4 col-lg-4 ">
                                <div class="thumbnail">
                                    <a href="{% url 'music:all_songs' album.id %}">
                                        {% if album.is_local_file %}
                                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                                        {% else %}
                                            <img src="{{ album.album_logo }}" class="img-responsive">
                                        {% endif %}
                                    </a>
                                    <div class="caption">
                                        <h2>{{ album.album_title }}</h2>
                                        <h4>{{ album.artist }}</h4>
                                        {# <a href="{% url 'music:display_all_in_album' album.id %}">{{ album.album_title }}</a>#}

                                        <a href="{% url 'music:all_songs' album.id %}"
                                           class="button-success pure-button">check
                                        </a>
                                        {# button's event needs form to active#}
                                        <form action="{% url 'music:delete_album' album.id %}" method="post"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                            <button type="submit" class="button-error pure-button">delete
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                        {% endfor %}

                    {% else %}
                        <h3>you have nothing to show</h3>
                        <div class="col-sm-12">
                            <br>
                            <a href="{% url 'music:create_album' %}">
                                <button type="button" class="btn btn-success">
                                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>

            </section>
        </div>
    </div>
</div>
</body>

templates/music/welcom_index.html
{% extends 'music/base.html' %}
{% block title %}welcome my world{% endblock %}
{% block body %}

{% endblock %}